name: Github CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: home-laboratory-runner

    steps:
      - uses: actions/checkout@v3
      - name: 'Build Project'
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm i
      - run: npm run build

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: FinWave Frontend
          path: .output/
  build-docker:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: FinWave Frontend
          path: ./
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build & Push Container'
        run: |
            docker build . --tag ghcr.io/FinWave-App/frontend:latest
            docker push ghcr.io/FinWave-App/frontend:latest